main: com.minersleague.main.Main
version: 0.0.08
name: Miners_League

commands:
  test:
    description: sends a Testmessage to Target
    usage: /test <Player>
  game:
    description: All Commands for the TowerDefense Minigame
    usage: /game <param> <param>
  announce:
    description: Sends an announcement.
    usage: /announce <Message>
  a:
    description: A thing.
    usage: /a <Player> <Message>
  addlore:
    description: Adds a lore.
    usage: /addlore <lore>
  rename:
    description: Renames the item you are holding.
    usage: /rename <name>