package com.minersleague.main.util;

import org.bukkit.Location;
import org.bukkit.Material;

/**
 * 
 * @author FelixVogel
 * @since 24/9/2016
 * <p>
 * @Info This is like the BukkitMaterials (Material) Class but only more Features! Including: All Block Possibilities that are possible in Minecraft, like Every-Block Direction and Type! It also comes with 2 Place Methods so these Block can be Placed in your World!
 *
 */
public enum BlockResource {
	
	Air(Material.AIR),
	Stone(Material.STONE),
	Granite(Material.STONE, 1),
	Polished_Granite(Material.STONE, 2),
	Diorite(Material.STONE, 3),
	Polished_Diorite(Material.STONE, 4),
	Andesite(Material.STONE, 3),
	Polished_Andesite(Material.STONE, 4),
	Grass_Block(Material.GRASS),
	Dirt(Material.DIRT),
	Coarse_Dirt(Material.DIRT, 1),
	Podzol(Material.DIRT, 2),
	Cobblestone(Material.COBBLESTONE),
	Oak_Planks(Material.WOOD),
	Spruce_Planks(Material.WOOD, 1),
	Birch_Planks(Material.WOOD, 2),
	Jungle_Planks(Material.WOOD, 3),
	Acacia_Planks(Material.WOOD, 4),
	Dark_Oak_Planks(Material.WOOD, 5),
	Bedrock(Material.BEDROCK),
	Sand(Material.SAND),
	Red_Sand(Material.SAND, 1),
	Gravel(Material.GRAVEL),
	Gold_Ore(Material.GOLD_ORE),
	Iron_Ore(Material.IRON_ORE),
	Coal_Ore(Material.COAL_ORE),
	Oak_Log(Material.LOG),
	Oak_Log_X(Material.LOG, 4),
	Oak_Log_Z(Material.LOG, 8),
	Oak_Log_ALL(Material.LOG, 12),
	Spruce_Log(Material.LOG, 1),
	Spruce_Log_X(Material.LOG, 5),
	Spruce_Log_Z(Material.LOG, 9),
	Spruce_Log_ALL(Material.LOG, 13),
	Birch_Log(Material.LOG, 2),
	Birch_Log_X(Material.LOG, 6),
	Birch_Log_Z(Material.LOG, 10),
	Birch_Log_ALL(Material.LOG, 14),
	Jungle_Log(Material.LOG, 3),
	Jungle_Log_X(Material.LOG, 7),
	Jungle_Log_Z(Material.LOG, 11),
	Jungle_Log_ALL(Material.LOG, 15),
	Sponge(Material.SPONGE),
	Wet_Sponge(Material.SPONGE, 1),
	Glass(Material.GLASS),
	Lapis_Lazuli_Ore(Material.LAPIS_ORE),
	Lapis_Lazuli_Block(Material.LAPIS_BLOCK),
	Sandstone(Material.SANDSTONE),
	Chiseled_Sandstone(Material.SANDSTONE, 1),
	Smooth_Sandstone(Material.SANDSTONE, 2),
	Wool(Material.WOOL),
	Orange_Wool(Material.WOOL, 1),
	Magenta_Wool(Material.WOOL, 2),
	Light_Blue_Wool(Material.WOOL, 3),
	Yellow_Wool(Material.WOOL, 4),
	Lime_Wool(Material.WOOL, 5),
	Pink_Wool(Material.WOOL, 6),
	Gray_Wool(Material.WOOL, 7),
	Light_Gray_Wool(Material.WOOL, 8),
	Cyan_Wool(Material.WOOL, 9),
	Purple_Wool(Material.WOOL, 10),
	Blue_Wool(Material.WOOL, 11),
	Brown_Wool(Material.WOOL, 12),
	Green_Wool(Material.WOOL, 13),
	Red_Wool(Material.WOOL, 14),
	Black_Wool(Material.WOOL, 15),
	Gold_Block(Material.GOLD_BLOCK),
	Iron_Block(Material.IRON_BLOCK),
	Stone_Slab(Material.STEP),
	Sandstone_Slab(Material.STEP, 1),
	Cobblestone_Slab(Material.STEP, 3),
	Bricks_Slab(Material.STEP, 4),
	Stone_Bricks_Slab(Material.STEP, 5),
	Nether_Brick_Slab(Material.STEP, 6),
	Quartz_Slab(Material.STEP, 7),
	Stone_Slab_UP(Material.STEP, 8),
	Sandstone_Slab_UP(Material.STEP, 9),
	Cobblestone_Slab_UP(Material.STEP, 11),
	Bricks_Slab_UP(Material.STEP, 12),
	Stone_Bricks_Slab_UP(Material.STEP, 13),
	Nether_Brick_Slab_UP(Material.STEP, 14),
	Quartz_Slab_UP(Material.STEP, 15),
	Bricks(Material.BRICK),
	Bookshelf(Material.BOOKSHELF),
	Moss_Stone(Material.MOSSY_COBBLESTONE),
	Obsidian(Material.OBSIDIAN),
	Oak_Stairs_East(Material.WOOD_STAIRS),
	Oak_Stairs_West(Material.WOOD_STAIRS, 1),
	Oak_Stairs_South(Material.WOOD_STAIRS, 2),
	Oak_Stairs_North(Material.WOOD_STAIRS, 3),
	Oak_Stairs_East_UP(Material.WOOD_STAIRS, 4),
	Oak_Stairs_West_UP(Material.WOOD_STAIRS, 5),
	Oak_Stairs_South_UP(Material.WOOD_STAIRS, 6),
	Oak_Stairs_North_UP(Material.WOOD_STAIRS, 7),
	Diamond_Ore(Material.DIAMOND_ORE),
	Diamond_Block(Material.DIAMOND_BLOCK),
	Cobblestone_Stairs_East(Material.COBBLESTONE_STAIRS),
	Cobblestone_Stairs_West(Material.COBBLESTONE_STAIRS, 1),
	Cobblestone_Stairs_South(Material.COBBLESTONE_STAIRS, 2),
	Cobblestone_Stairs_North(Material.COBBLESTONE_STAIRS, 3),
	Cobblestone_Stairs_East_UP(Material.COBBLESTONE_STAIRS, 4),
	Cobblestone_Stairs_West_UP(Material.COBBLESTONE_STAIRS, 5),
	Cobblestone_Stairs_South_UP(Material.COBBLESTONE_STAIRS, 6),
	Cobblestone_Stairs_North_UP(Material.COBBLESTONE_STAIRS, 7),
	Redstone_Ore(Material.REDSTONE_ORE),
	Glowing_Redstone_Ore(Material.GLOWING_REDSTONE_ORE),
	Ice(Material.ICE),
	Snow_Block(Material.SNOW_BLOCK),
	Clay_Block(Material.CLAY),
	Pumkin(Material.PUMPKIN),
	Netherrack(Material.NETHERRACK),
	Soul_Sand(Material.SOUL_SAND),
	Glowstone(Material.GLOWSTONE),
	JackOLantern(Material.JACK_O_LANTERN),
	White_Glass(Material.STAINED_GLASS),
	Orange_Glass(Material.STAINED_GLASS, 1),
	Magenta_Glass(Material.STAINED_GLASS, 2),
	Light_Blue_Glass(Material.STAINED_GLASS, 3),
	Yellow_Glass(Material.STAINED_GLASS, 4),
	Lime_Glass(Material.STAINED_GLASS, 5),
	Pink_Glass(Material.STAINED_GLASS, 6),
	Gray_Glass(Material.STAINED_GLASS, 7),
	Light_Gray_Glass(Material.STAINED_GLASS, 8),
	Cyan_Glass(Material.STAINED_GLASS, 9),
	Purple_Glass(Material.STAINED_GLASS, 10),
	Blue_Glass(Material.STAINED_GLASS, 11),
	Brown_Glass(Material.STAINED_GLASS, 12),
	Green_Glass(Material.STAINED_GLASS, 13),
	Red_Glass(Material.STAINED_GLASS, 14),
	Black_Glass(Material.STAINED_GLASS, 15),
	Stone_Bricks(Material.SMOOTH_BRICK),
	Mossy_Stone_Bricks(Material.SMOOTH_BRICK, 1),
	Cracked_Stone_Bricks(Material.SMOOTH_BRICK, 2),
	Chiseled_Stone_Bricks(Material.SMOOTH_BRICK, 3),
	Melon(Material.MELON),
	Brick_Stairs_East(Material.BRICK_STAIRS),
	Brick_Stairs_West(Material.BRICK_STAIRS, 1),
	Brick_Stairs_South(Material.BRICK_STAIRS, 2),
	Brick_Stairs_North(Material.BRICK_STAIRS, 3),
	Brick_Stairs_East_UP(Material.BRICK_STAIRS, 4),
	Brick_Stairs_West_UP(Material.BRICK_STAIRS, 5),
	Brick_Stairs_South_UP(Material.BRICK_STAIRS, 6),
	Brick_Stairs_North_UP(Material.BRICK_STAIRS, 7),
	Stone_Brick_Stairs_East(Material.SMOOTH_STAIRS),
	Stone_Brick_Stairs_West(Material.SMOOTH_STAIRS, 1),
	Stone_Brick_Stairs_South(Material.SMOOTH_STAIRS, 2),
	Stone_Brick_Stairs_North(Material.SMOOTH_STAIRS, 3),
	Stone_Brick_Stairs_East_UP(Material.SMOOTH_STAIRS, 4),
	Stone_Brick_Stairs_West_UP(Material.SMOOTH_STAIRS, 5),
	Stone_Brick_Stairs_South_UP(Material.SMOOTH_STAIRS, 6),
	Stone_Brick_Stairs_North_UP(Material.SMOOTH_STAIRS, 7),
	Mycelium(Material.MYCEL),
	Nether_Brick(Material.NETHER_BRICK),
	Nether_Brick_Stairs_East(Material.NETHER_BRICK_STAIRS),
	Nether_Brick_Stairs_West(Material.NETHER_BRICK_STAIRS, 1),
	Nether_Brick_Stairs_South(Material.NETHER_BRICK_STAIRS, 2),
	Nether_Brick_Stairs_North(Material.NETHER_BRICK_STAIRS, 3),
	Nether_Brick_Stairs_East_UP(Material.NETHER_BRICK_STAIRS, 4),
	Nether_Brick_Stairs_West_UP(Material.NETHER_BRICK_STAIRS, 5),
	Nether_Brick_Stairs_South_UP(Material.NETHER_BRICK_STAIRS, 6),
	Nether_Brick_Stairs_North_UP(Material.NETHER_BRICK_STAIRS, 7),
	End_Stone(Material.ENDER_STONE),
	Oak_Slab(Material.WOOD_STEP),
	Spruce_Slab(Material.WOOD_STEP, 1),
	Birch_Slab(Material.WOOD_STEP, 2),
	Jungle_Slab(Material.WOOD_STEP, 3),
	Acacia_Slab(Material.WOOD_STEP, 4),
	Dark_Oak_Slab(Material.WOOD_STEP, 5),
	Oak_Slab_UP(Material.WOOD_STEP, 8),
	Spruce_Slab_UP(Material.WOOD_STEP, 9),
	Birch_Slab_UP(Material.WOOD_STEP, 10),
	Jungle_Slab_UP(Material.WOOD_STEP, 11),
	Acacia_Slab_UP(Material.WOOD_STEP, 12),
	Dark_Oak_Slab_UP(Material.WOOD_STEP, 13),
	Sandstone_Stairs_East(Material.SANDSTONE_STAIRS),
	Sandstone_Stairs_West(Material.SANDSTONE_STAIRS, 1),
	Sandstone_Stairs_South(Material.SANDSTONE_STAIRS, 2),
	Sandstone_Stairs_North(Material.SANDSTONE_STAIRS, 3),
	Sandstone_Stairs_East_UP(Material.SANDSTONE_STAIRS, 4),
	Sandstone_Stairs_West_UP(Material.SANDSTONE_STAIRS, 5),
	Sandstone_Stairs_South_UP(Material.SANDSTONE_STAIRS, 6),
	Sandstone_Stairs_North_UP(Material.SANDSTONE_STAIRS, 7),
	Emerald_Ore(Material.EMERALD_ORE),
	Emerald_Block(Material.EMERALD_BLOCK),
	Spruce_Stairs_East(Material.SPRUCE_WOOD_STAIRS),
	Spruce_Stairs_West(Material.SPRUCE_WOOD_STAIRS, 1),
	Spruce_Stairs_South(Material.SPRUCE_WOOD_STAIRS, 2),
	Spruce_Stairs_North(Material.SPRUCE_WOOD_STAIRS, 3),
	Spruce_Stairs_East_UP(Material.SPRUCE_WOOD_STAIRS, 4),
	Spruce_Stairs_West_UP(Material.SPRUCE_WOOD_STAIRS, 5),
	Spruce_Stairs_South_UP(Material.SPRUCE_WOOD_STAIRS, 6),
	Spruce_Stairs_North_UP(Material.SPRUCE_WOOD_STAIRS, 7),
	Birch_Stairs_East(Material.BIRCH_WOOD_STAIRS),
	Birch_Stairs_West(Material.BIRCH_WOOD_STAIRS, 1),
	Birch_Stairs_South(Material.BIRCH_WOOD_STAIRS, 2),
	Birch_Stairs_North(Material.BIRCH_WOOD_STAIRS, 3),
	Birch_Stairs_East_UP(Material.BIRCH_WOOD_STAIRS, 4),
	Birch_Stairs_West_UP(Material.BIRCH_WOOD_STAIRS, 5),
	Birch_Stairs_South_UP(Material.BIRCH_WOOD_STAIRS, 6),
	Birch_Stairs_North_UP(Material.BIRCH_WOOD_STAIRS, 7),
	Jungle_Stairs_East(Material.JUNGLE_WOOD_STAIRS),
	Jungle_Stairs_West(Material.JUNGLE_WOOD_STAIRS, 1),
	Jungle_Stairs_South(Material.JUNGLE_WOOD_STAIRS, 2),
	Jungle_Stairs_North(Material.JUNGLE_WOOD_STAIRS, 3),
	Jungle_Stairs_East_UP(Material.JUNGLE_WOOD_STAIRS, 4),
	Jungle_Stairs_West_UP(Material.JUNGLE_WOOD_STAIRS, 5),
	Jungle_Stairs_South_UP(Material.JUNGLE_WOOD_STAIRS, 6),
	Jungle_Stairs_North_UP(Material.JUNGLE_WOOD_STAIRS, 7),
	Cobblestone_Wall(Material.COBBLE_WALL),
	Mossy_Cobblestone_Wall(Material.COBBLE_WALL, 1),
	Nether_Quartz_Ore(Material.QUARTZ_ORE),
	Quartz_Block(Material.QUARTZ_BLOCK),
	Chiseled_Quartz_Block(Material.QUARTZ_BLOCK, 1),
	Pillar_Quartz_Block(Material.QUARTZ_BLOCK, 2),
	Pillar_Quartz_Block_X(Material.QUARTZ_BLOCK, 3),
	Pillar_Quartz_Block_Z(Material.QUARTZ_BLOCK, 4),
	Quartz_Stairs_East(Material.QUARTZ_STAIRS),
	Quartz_Stairs_West(Material.QUARTZ_STAIRS, 1),
	Quartz_Stairs_South(Material.QUARTZ_STAIRS, 2),
	Quartz_Stairs_North(Material.QUARTZ_STAIRS, 3),
	Quartz_Stairs_East_UP(Material.QUARTZ_STAIRS, 4),
	Quartz_Stairs_West_UP(Material.QUARTZ_STAIRS, 5),
	Quartz_Stairs_South_UP(Material.QUARTZ_STAIRS, 6),
	Quartz_Stairs_North_UP(Material.QUARTZ_STAIRS, 7),
	White_Hardened_Clay(Material.STAINED_CLAY),
	Orange_Hardened_Clay(Material.STAINED_CLAY, 1),
	Magenta_Hardened_Clay(Material.STAINED_CLAY, 2),
	Light_Blue_Hardened_Clay(Material.STAINED_CLAY, 3),
	Yellow_Hardened_Clay(Material.STAINED_CLAY, 4),
	Lime_Hardened_Clay(Material.STAINED_CLAY, 5),
	Pink_Hardened_Clay(Material.STAINED_CLAY, 6),
	Gray_Hardened_Clay(Material.STAINED_CLAY, 7),
	Light_Gray_Hardened_Clay(Material.STAINED_CLAY, 8),
	Cyan_Hardened_Clay(Material.STAINED_CLAY, 9),
	Purple_Hardened_Clay(Material.STAINED_CLAY, 10),
	Blue_Hardened_Clay(Material.STAINED_CLAY, 11),
	Brown_Hardened_Clay(Material.STAINED_CLAY, 12),
	Green_Hardened_Clay(Material.STAINED_CLAY, 13),
	Red_Hardened_Clay(Material.STAINED_CLAY, 14),
	Black_Hardened_Clay(Material.STAINED_CLAY, 15),
	Acacia_Log(Material.LOG_2),
	Acacia_Log_X(Material.LOG_2, 4),
	Acacia_Log_Z(Material.LOG_2, 8),
	Acacia_Log_ALL(Material.LOG_2, 12),
	Dark_Oak_Log(Material.LOG_2, 1),
	Dark_Oak_Log_X(Material.LOG_2, 5),
	Dark_Oak_Log_Z(Material.LOG_2, 9),
	Dark_Oak_Log_ALL(Material.LOG_2, 13),
	Acacia_Stairs_East(Material.ACACIA_STAIRS),
	Acacia_Stairs_West(Material.ACACIA_STAIRS, 1),
	Acacia_Stairs_South(Material.ACACIA_STAIRS, 2),
	Acacia_Stairs_North(Material.ACACIA_STAIRS, 3),
	Acacia_Stairs_East_UP(Material.ACACIA_STAIRS, 4),
	Acacia_Stairs_West_UP(Material.ACACIA_STAIRS, 5),
	Acacia_Stairs_South_UP(Material.ACACIA_STAIRS, 6),
	Acacia_Stairs_North_UP(Material.ACACIA_STAIRS, 7),
	Dark_Oak_Stairs_East(Material.DARK_OAK_STAIRS),
	Dark_Oak_Stairs_West(Material.DARK_OAK_STAIRS, 1),
	Dark_Oak_Stairs_South(Material.DARK_OAK_STAIRS, 2),
	Dark_Oak_Stairs_North(Material.DARK_OAK_STAIRS, 3),
	Dark_Oak_Stairs_East_UP(Material.DARK_OAK_STAIRS, 4),
	Dark_Oak_Stairs_West_UP(Material.DARK_OAK_STAIRS, 5),
	Dark_Oak_Stairs_South_UP(Material.DARK_OAK_STAIRS, 6),
	Dark_Oak_Stairs_North_UP(Material.DARK_OAK_STAIRS, 7),
	Prismarine(Material.PRISMARINE),
	Prismarine_Bricks(Material.PRISMARINE, 1),
	Dark_Prismarine(Material.PRISMARINE, 2),
	Sea_Lantern(Material.SEA_LANTERN),
	Hay_Bale(Material.HAY_BLOCK),
	Hardened_Clay(Material.HARD_CLAY),
	Coal_Block(Material.COAL_BLOCK),
	Packed_Ice(Material.PACKED_ICE),
	Red_Sandstone(Material.RED_SANDSTONE),
	Chiseled_Red_Sandstone(Material.RED_SANDSTONE, 1),
	Smooth_Red_Sandstone(Material.RED_SANDSTONE, 2),
	Red_Sandstone_Stairs_East(Material.RED_SANDSTONE_STAIRS),
	Red_Sandstone_Stairs_West(Material.RED_SANDSTONE_STAIRS, 1),
	Red_Sandstone_Stairs_South(Material.RED_SANDSTONE_STAIRS, 2),
	Red_Sandstone_Stairs_North(Material.RED_SANDSTONE_STAIRS, 3),
	Red_Sandstone_Stairs_East_UP(Material.RED_SANDSTONE_STAIRS, 4),
	Red_Sandstone_Stairs_West_UP(Material.RED_SANDSTONE_STAIRS, 5),
	Red_Sandstone_Stairs_South_UP(Material.RED_SANDSTONE_STAIRS, 6),
	Red_Sandstone_Stairs_North_UP(Material.RED_SANDSTONE_STAIRS, 7),
	Red_Sandstone_Slab(Material.STONE_SLAB2),
	Red_Sandstone_Slab_UP(Material.STONE_SLAB2, 8),
	Purpur_Block(Material.PURPUR_BLOCK),
	Purpur_Pillar(Material.PURPUR_PILLAR),
	Purpur_Pillar_X(Material.PURPUR_PILLAR, 4),
	Purpur_Pillar_Z(Material.PURPUR_PILLAR, 8),
	Purpur_Stairs_East(Material.PURPUR_STAIRS),
	Purpur_Stairs_West(Material.PURPUR_STAIRS, 1),
	Purpur_Stairs_South(Material.PURPUR_STAIRS, 2),
	Purpur_Stairs_North(Material.PURPUR_STAIRS, 3),
	Purpur_Stairs_East_UP(Material.PURPUR_STAIRS, 4),
	Purpur_Stairs_West_UP(Material.PURPUR_STAIRS, 5),
	Purpur_Stairs_South_UP(Material.PURPUR_STAIRS, 6),
	Purpur_Stairs_North_UP(Material.PURPUR_STAIRS, 7),
	Purpur_Slab(Material.PURPUR_SLAB),
	Purpur_Slab_UP(Material.PURPUR_SLAB, 8),
	End_Stone_Bricks(Material.END_BRICKS),
	Oak_Sapling(Material.SAPLING),
	Spruce_Sapling(Material.SAPLING, 1),
	Birch_Sapling(Material.SAPLING, 2),
	Jungle_Sapling(Material.SAPLING, 3),
	Acacia_Sapling(Material.SAPLING, 4),
	Dark_Oak_Sapling(Material.SAPLING, 5),
	Oak_Leaves(Material.LEAVES),
	Spruce_Leaves(Material.LEAVES, 1),
	Birch_Leaves(Material.LEAVES, 2),
	Jungle_Leaves(Material.LEAVES, 3),
	Cobweb(Material.WEB),
	Grass(Material.LONG_GRASS, 1),
	Fern(Material.LONG_GRASS, 2),
	Dead_Bush(Material.DEAD_BUSH),
	Dandelion(Material.YELLOW_FLOWER),
	Poppy(Material.RED_ROSE),
	Blue_Orchid(Material.RED_ROSE, 1),
	Allium(Material.RED_ROSE, 2),
	Azure_Bluet(Material.RED_ROSE, 3),
	Red_Tulip(Material.RED_ROSE, 4),
	Orange_Tulip(Material.RED_ROSE, 5),
	White_Tulip(Material.RED_ROSE, 6),
	Pink_Tulip(Material.RED_ROSE, 7),
	Oxeye_Daisy(Material.RED_ROSE, 8),
	Brown_Mushroom(Material.BROWN_MUSHROOM),
	Red_Mushroom(Material.RED_MUSHROOM),
	Torch(Material.TORCH),
	Torch_East(Material.TORCH, 1),
	Torch_West(Material.TORCH, 2),
	Torch_South(Material.TORCH, 3),
	Torch_North(Material.TORCH, 4),
	Chest_North(Material.CHEST),
	Chest_South(Material.CHEST, 3),
	Chest_West(Material.CHEST, 4),
	Chest_East(Material.CHEST, 5),
	Crafting_Table(Material.WORKBENCH),
	Furnace_North(Material.FURNACE),
	Furnace_South(Material.FURNACE, 3),
	Furnace_West(Material.FURNACE, 4),
	Furnace_East(Material.FURNACE, 5),
	Burning_Furnace_North(Material.BURNING_FURNACE),
	Burning_Furnace_South(Material.BURNING_FURNACE, 3),
	Burning_Furnace_West(Material.BURNING_FURNACE, 4),
	Burning_Furnace_East(Material.BURNING_FURNACE, 5),
	Ladder_North(Material.FURNACE),
	Ladder_South(Material.FURNACE, 3),
	Ladder_West(Material.FURNACE, 4),
	Ladder_East(Material.FURNACE, 5),
	Snow_Layers_1(Material.SNOW, 0),
	Snow_Layers_2(Material.SNOW, 1),
	Snow_Layers_3(Material.SNOW, 2),
	Snow_Layers_4(Material.SNOW, 3),
	Snow_Layers_5(Material.SNOW, 4),
	Snow_Layers_6(Material.SNOW, 5),
	Snow_Layers_7(Material.SNOW, 6),
	Cactus(Material.CACTUS),
	Jukebox(Material.JUKEBOX),
	Oak_Fence(Material.FENCE),
	Stone_Monster_EGG(Material.MONSTER_EGGS),
	Cobblestone_Monster_Egg(Material.MONSTER_EGGS, 1),
	Stone_Brick_Monster_Egg(Material.MONSTER_EGGS, 2),
	Mossy_Stone_Brick_Monster_Egg(Material.MONSTER_EGGS, 3),
	Cracked_Stone_Brick_Monster_Egg(Material.MONSTER_EGGS, 4),
	Chiseled_Stone_Brick_Monster_Egg(Material.MONSTER_EGGS, 5),
	Iron_Bars(Material.IRON_FENCE),
	Glass_Pane(Material.THIN_GLASS),
	Vines(Material.VINE),
	Vines_South(Material.VINE, 1),
	Vines_West(Material.VINE, 2),
	Vines_South_West(Material.VINE, 3),
	Vines_North(Material.VINE, 4),
	Vines_North_South(Material.VINE, 5),
	Vines_North_West(Material.VINE, 6),
	Vines_North_South_West(Material.VINE, 7),
	Vines_East(Material.VINE, 8),
	Vines_East_South(Material.VINE, 9),
	Vines_East_West(Material.VINE, 10),
	Vines_East_South_West(Material.VINE, 11),
	Vines_East_North(Material.VINE, 12),
	Vines_East_North_South(Material.VINE, 13),
	Vines_East_North_West(Material.VINE, 14),
	Vines_East_North_South_West(Material.VINE, 15),
	Lily_Pad(Material.WATER_LILY),
	Nether_Brick_Fence(Material.NETHER_FENCE),
	Enchantment_Table(Material.ENCHANTMENT_TABLE),
	End_Portal_Frame_X(Material.ENDER_PORTAL_FRAME, 1),
	End_Portal_Frame_Z(Material.ENDER_PORTAL_FRAME),
	Ender_Chest_North(Material.ENDER_CHEST),
	Ender_Chest_South(Material.ENDER_CHEST, 3),
	Ender_Chest_West(Material.ENDER_CHEST, 4),
	Ender_Chest_East(Material.ENDER_CHEST, 5),
	Anvil_X(Material.ANVIL, 1),
	Anvil_Z(Material.ANVIL),
	Slightly_Damaged_Anvil_X(Material.ANVIL, 5),
	Slightly_Damaged_Anvil_Z(Material.ANVIL, 4),
	Very_Damaged_Anvil_X(Material.ANVIL, 9),
	Very_Damaged_Anvil_Z(Material.ANVIL, 8),
	White_Glass_Pane(Material.STAINED_GLASS_PANE),
	Orange_Glass_Pane(Material.STAINED_GLASS_PANE, 1),
	Magenta_Glass_Pane(Material.STAINED_GLASS_PANE, 2),
	Light_Blue_Glass_Pane(Material.STAINED_GLASS_PANE, 3),
	Yellow_Glass_Pane(Material.STAINED_GLASS_PANE, 4),
	Lime_Glass_Pane(Material.STAINED_GLASS_PANE, 5),
	Pink_Glass_Pane(Material.STAINED_GLASS_PANE, 6),
	Gray_Glass_Pane(Material.STAINED_GLASS_PANE, 7),
	Light_Gray_Glass_Pane(Material.STAINED_GLASS_PANE, 8),
	Cyan_Glass_Pane(Material.STAINED_GLASS_PANE, 9),
	Purple_Glass_Pane(Material.STAINED_GLASS_PANE, 10),
	Blue_Glass_Pane(Material.STAINED_GLASS_PANE, 11),
	Brown_Glass_Pane(Material.STAINED_GLASS_PANE, 12),
	Green_Glass_Pane(Material.STAINED_GLASS_PANE, 13),
	Red_Glass_Pane(Material.STAINED_GLASS_PANE, 14),
	Black_Glass_Pane(Material.STAINED_GLASS_PANE, 15),
	Acacia_Leaves(Material.LEAVES_2),
	Dark_Oak_Leaves(Material.LEAVES_2, 1),
	Slime_Block(Material.SLIME_BLOCK),
	White_Carpet(Material.CARPET),
	Orange_Carpet(Material.CARPET, 1),
	Magenta_Carpet(Material.CARPET, 2),
	Light_Blue_Carpet(Material.CARPET, 3),
	Yellow_Carpet(Material.CARPET, 4),
	Lime_Carpet(Material.CARPET, 5),
	Pink_Carpet(Material.CARPET, 6),
	Gray_Carpet(Material.CARPET, 7),
	Light_Gray_Carpet(Material.CARPET, 8),
	Cyan_Carpet(Material.CARPET, 9),
	Purple_Carpet(Material.CARPET, 10),
	Blue_Carpet(Material.CARPET, 11),
	Brown_Carpet(Material.CARPET, 12),
	Green_Carpet(Material.CARPET, 13),
	Red_Carpet(Material.CARPET, 14),
	Black_Carpet(Material.CARPET, 15),
	Sunflower(Material.DOUBLE_PLANT),
	Lilac(Material.DOUBLE_PLANT, 1),
	Double_Tallgrass(Material.DOUBLE_PLANT, 2),
	Large_Fern(Material.DOUBLE_PLANT, 3),
	Rose_Bush(Material.DOUBLE_PLANT, 4),
	Peony(Material.DOUBLE_PLANT, 5),
	Spruce_Fence(Material.SPRUCE_FENCE),
	Birch_Fence(Material.BIRCH_FENCE),
	Jungle_Fence(Material.JUNGLE_FENCE),
	Dark_Oak_Fence(Material.DARK_OAK_FENCE),
	Acacia_Fence(Material.ACACIA_FENCE),
	End_Rod_UP(Material.END_ROD),
	End_Rod_North(Material.END_ROD, 2),
	End_Rod_South(Material.END_ROD, 3),
	End_Rod_West(Material.END_ROD, 4),
	End_Rod_East(Material.END_ROD, 5),
	End_Rod_Down(Material.END_ROD, 6),
	Chorus_Plant(Material.CHORUS_PLANT),
	Chorus_Flower(Material.CHORUS_FLOWER),
	Standing_Sign_South(Material.SIGN_POST),
	Standing_Sign_West(Material.SIGN_POST, 4),
	Standing_Sign_North(Material.SIGN_POST, 8),
	Standing_Sign_East(Material.SIGN_POST, 12),
	Wall_Sign_North(Material.WALL_SIGN),
	Wall_Sign_South(Material.WALL_SIGN, 1),
	Wall_Sign_West(Material.WALL_SIGN, 4),
	Wall_Sign_East(Material.WALL_SIGN, 5),
	Bed_Foot_North(Material.BED_BLOCK),
	Bed_Foot_West(Material.BED_BLOCK, 1),
	Bed_Foot_East(Material.BED_BLOCK, 3),
	Bed_Foot_South(Material.BED_BLOCK, 4),
	Bed_Head_South(Material.BED_BLOCK, 8),
	Bed_Head_West(Material.BED_BLOCK, 9),
	Bed_Head_North(Material.BED_BLOCK, 10),
	Bed_Head_East(Material.BED_BLOCK, 11),
	Flower_Pot(Material.FLOWER_POT),
	Skeleton_Skull(Material.SKULL),
	Wither_Skeleton_Skull(Material.SKULL, 1),
	Zombie_Head(Material.SKULL, 2),
	Head(Material.SKULL, 3),
	Creeper_Head(Material.SKULL, 4),
	Dragon_Head(Material.SKULL, 5),
	Dispenser_North(Material.DISPENSER),
	Dispenser_South(Material.DISPENSER, 3),
	Dispenser_West(Material.DISPENSER, 4),
	Dispenser_East(Material.DISPENSER, 5),
	Dispenser_Down(Material.DISPENSER, 6),
	Dispenser_UP(Material.DISPENSER, 7),
	Note_Block(Material.NOTE_BLOCK),
	Piston_North(Material.PISTON_BASE),
	Piston_UP(Material.PISTON_BASE, 1),
	Piston_South(Material.PISTON_BASE, 3),
	Piston_West(Material.PISTON_BASE, 4),
	Piston_East(Material.PISTON_BASE, 5),
	Piston_Down(Material.PISTON_BASE, 16),
	Extended_Piston_Down(Material.PISTON_BASE, 8),
	Extended_Piston_UP(Material.PISTON_BASE, 9),
	Extended_Piston_North(Material.PISTON_BASE, 10),
	Extended_Piston_South(Material.PISTON_BASE, 11),
	Extended_Piston_West(Material.PISTON_BASE, 12),
	Extended_Piston_East(Material.PISTON_BASE, 13),
	Sticky_Piston_North(Material.PISTON_STICKY_BASE),
	Sticky_Piston_UP(Material.PISTON_STICKY_BASE, 1),
	Sticky_Piston_South(Material.PISTON_STICKY_BASE, 3),
	Sticky_Piston_West(Material.PISTON_STICKY_BASE, 4),
	Sticky_Piston_East(Material.PISTON_STICKY_BASE, 5),
	Sticky_Piston_Down(Material.PISTON_STICKY_BASE, 16),
	Extended_Sticky_Piston_Down(Material.PISTON_STICKY_BASE, 8),
	Extended_Sticky_Piston_UP(Material.PISTON_STICKY_BASE, 9),
	Extended_Sticky_Piston_North(Material.PISTON_STICKY_BASE, 10),
	Extended_Sticky_Piston_South(Material.PISTON_STICKY_BASE, 11),
	Extended_Sticky_Piston_West(Material.PISTON_STICKY_BASE, 12),
	Extended_Sticky_Piston_East(Material.PISTON_STICKY_BASE, 13),
	Piston_Head_North(Material.PISTON_EXTENSION),
	Piston_Head_UP(Material.PISTON_EXTENSION, 1),
	Piston_Head_South(Material.PISTON_EXTENSION, 3),
	Piston_Head_West(Material.PISTON_EXTENSION, 4),
	Piston_Head_East(Material.PISTON_EXTENSION, 5),
	Piston_Head_Down(Material.PISTON_EXTENSION, 16),
	Sticky_Piston_Head_Down(Material.PISTON_EXTENSION, 8),
	Sticky_Piston_Head_UP(Material.PISTON_EXTENSION, 9),
	Sticky_Piston_Head_North(Material.PISTON_EXTENSION, 10),
	Sticky_Piston_Head_South(Material.PISTON_EXTENSION, 11),
	Sticky_Piston_Head_West(Material.PISTON_EXTENSION, 12),
	Sticky_Piston_Head_East(Material.PISTON_EXTENSION, 13),
	TNT(Material.TNT),
	Lever_North(Material.LEVER),
	Lever_East(Material.LEVER, 1),
	Lever_West(Material.LEVER, 2),
	Lever_South(Material.LEVER, 3),
	Lever_Down_Z(Material.LEVER, 5),
	Lever_Down_X(Material.LEVER, 6),
	Lever_UP_Z(Material.LEVER, 7),
	Lever_UP_X(Material.LEVER, 16),
	Powered_Lever_UP_X(Material.LEVER, 8),
	Powered_Lever_East(Material.LEVER, 9),
	Powered_Lever_West(Material.LEVER, 10),
	Powered_Lever_South(Material.LEVER, 11),
	Powered_Lever_North(Material.LEVER, 12),
	Powered_Lever_Down_Z(Material.LEVER, 13),
	Powered_Lever_Down_X(Material.LEVER, 14),
	Powered_Lever_UP_Z(Material.LEVER, 15),
	Stone_Pressure_Plate(Material.STONE_PLATE),
	Powered_Stone_Pressure_Plate(Material.STONE_PLATE, 1),
	Wooden_Pressure_Plate(Material.WOOD_PLATE),
	Powered_Wooden_Pressure_Plate(Material.WOOD_PLATE, 1),
	Redstone_Torch_OFF(Material.REDSTONE_TORCH_OFF),
	Redstone_Torch_East_OFF(Material.REDSTONE_TORCH_OFF, 1),
	Redstone_Torch_West_OFF(Material.REDSTONE_TORCH_OFF, 2),
	Redstone_Torch_South_OFF(Material.REDSTONE_TORCH_OFF, 3),
	Redstone_Torch_North_OFF(Material.REDSTONE_TORCH_OFF, 4),
	Redstone_Torch_ON(Material.REDSTONE_TORCH_ON),
	Redstone_Torch_East_ON(Material.REDSTONE_TORCH_ON, 1),
	Redstone_Torch_West_ON(Material.REDSTONE_TORCH_ON, 2),
	Redstone_Torch_South_ON(Material.REDSTONE_TORCH_ON, 3),
	Redstone_Torch_North_ON(Material.REDSTONE_TORCH_ON, 4),
	Stone_Button_North(Material.STONE_BUTTON),
	Stone_Button_East(Material.STONE_BUTTON, 1),
	Stone_Button_West(Material.STONE_BUTTON, 2),
	Stone_Button_South(Material.STONE_BUTTON, 3),
	Stone_Button_Down(Material.STONE_BUTTON, 5),
	Stone_Button_UP(Material.STONE_BUTTON, 16),
	Powered_Stone_Button_UP(Material.STONE_BUTTON, 8),
	Powered_Stone_Button_East(Material.STONE_BUTTON, 9),
	Powered_Stone_Button_West(Material.STONE_BUTTON, 10),
	Powered_Stone_Button_South(Material.STONE_BUTTON, 11),
	Powered_Stone_Button_North(Material.STONE_BUTTON, 12),
	Powered_Stone_Button_Down(Material.STONE_BUTTON, 13),
	Wooden_Trapdoor_North_Down(Material.TRAP_DOOR),
	Wooden_Trapdoor_South_Down(Material.TRAP_DOOR, 1),
	Wooden_Trapdoor_West_Down(Material.TRAP_DOOR, 2),
	Wooden_Trapdoor_East_Down(Material.TRAP_DOOR, 3),
	Wooden_Trapdoor_North_Down_OPEN(Material.TRAP_DOOR, 4),
	Wooden_Trapdoor_South_Down_OPEN(Material.TRAP_DOOR, 5),
	Wooden_Trapdoor_West_Down_OPEN(Material.TRAP_DOOR, 6),
	Wooden_Trapdoor_East_Down_OPEN(Material.TRAP_DOOR, 7),
	Wooden_Trapdoor_North_UP(Material.TRAP_DOOR, 8),
	Wooden_Trapdoor_South_UP(Material.TRAP_DOOR, 9),
	Wooden_Trapdoor_West_UP(Material.TRAP_DOOR, 10),
	Wooden_Trapdoor_East_UP(Material.TRAP_DOOR, 11),
	Wooden_Trapdoor_North_UP_OPEN(Material.TRAP_DOOR, 12),
	Wooden_Trapdoor_South_UP_OPEN(Material.TRAP_DOOR, 13),
	Wooden_Trapdoor_West_UP_OPEN(Material.TRAP_DOOR, 14),
	Wooden_Trapdoor_East_UP_OPEN(Material.TRAP_DOOR, 15),
	Oak_Fence_Gate_Z(Material.FENCE_GATE, 2),
	Oak_Fence_Gate_X(Material.FENCE_GATE, 3),
	Oak_Fence_Gate_South_OPEN(Material.FENCE_GATE, 4),
	Oak_Fence_Gate_West_OPEN(Material.FENCE_GATE, 5),
	Oak_Fence_Gate_North_OPEN(Material.FENCE_GATE, 6),
	Oak_Fence_Gate_East_OPEN(Material.FENCE_GATE, 7),
	Redstone_Lamp_OFF(Material.REDSTONE_LAMP_OFF),
	Redstone_Lamp_ON(Material.REDSTONE_LAMP_ON),
	Tripwire_Hook_West(Material.TRIPWIRE_HOOK, 1),
	Tripwire_Hook_North(Material.TRIPWIRE_HOOK, 2),
	Tripwire_Hook_East(Material.TRIPWIRE_HOOK, 3),
	Tripwire_Hook_South(Material.TRIPWIRE_HOOK, 16),
	Tripwire_Hook_South_Attached_OFF(Material.TRIPWIRE_HOOK, 4),
	Tripwire_Hook_West_Attached_OFF(Material.TRIPWIRE_HOOK, 5),
	Tripwire_Hook_North_Attached_OFF(Material.TRIPWIRE_HOOK, 6),
	Tripwire_Hook_East_Attached_OFF(Material.TRIPWIRE_HOOK, 7),
	Tripwire_Hook_South_ON(Material.TRIPWIRE_HOOK, 8),
	Tripwire_Hook_West_ON(Material.TRIPWIRE_HOOK, 9),
	Tripwire_Hook_North_ON(Material.TRIPWIRE_HOOK, 10),
	Tripwire_Hook_East_ON(Material.TRIPWIRE_HOOK, 11),
	Tripwire_Hook_South_Attached_ON(Material.TRIPWIRE_HOOK, 12),
	Tripwire_Hook_West_Attached_ON(Material.TRIPWIRE_HOOK, 13),
	Tripwire_Hook_North_Attached_ON(Material.TRIPWIRE_HOOK, 14),
	Tripwire_Hook_East_Attached_ON(Material.TRIPWIRE_HOOK, 15),
	Wooden_Button_North(Material.WOOD_BUTTON),
	Wooden_Button_East(Material.WOOD_BUTTON, 1),
	Wooden_Button_West(Material.WOOD_BUTTON, 2),
	Wooden_Button_South(Material.WOOD_BUTTON, 3),
	Wooden_Button_Down(Material.WOOD_BUTTON, 5),
	Wooden_Button_UP(Material.WOOD_BUTTON, 16),
	Powered_Wooden_Button_UP(Material.WOOD_BUTTON, 8),
	Powered_Wooden_Button_East(Material.WOOD_BUTTON, 9),
	Powered_Wooden_Button_West(Material.WOOD_BUTTON, 10),
	Powered_Wooden_Button_South(Material.WOOD_BUTTON, 11),
	Powered_Wooden_Button_North(Material.WOOD_BUTTON, 12),
	Powered_Wooden_Button_Down(Material.WOOD_BUTTON, 13),
	Trapped_Chest_North(Material.TRAPPED_CHEST),
	Trapped_Chest_South(Material.TRAPPED_CHEST, 3),
	Trapped_Chest_West(Material.TRAPPED_CHEST, 4),
	Trapped_Chest_East(Material.TRAPPED_CHEST, 5),
	Weighted_Pressure_Plate_Light(Material.GOLD_PLATE),
	Weighted_Pressure_Plate_Light_Power_1(Material.GOLD_PLATE, 1),
	Weighted_Pressure_Plate_Light_Power_2(Material.GOLD_PLATE, 2),
	Weighted_Pressure_Plate_Light_Power_3(Material.GOLD_PLATE, 3),
	Weighted_Pressure_Plate_Light_Power_4(Material.GOLD_PLATE, 4),
	Weighted_Pressure_Plate_Light_Power_5(Material.GOLD_PLATE, 5),
	Weighted_Pressure_Plate_Light_Power_6(Material.GOLD_PLATE, 6),
	Weighted_Pressure_Plate_Light_Power_7(Material.GOLD_PLATE, 7),
	Weighted_Pressure_Plate_Light_Power_8(Material.GOLD_PLATE, 8),
	Weighted_Pressure_Plate_Light_Power_9(Material.GOLD_PLATE, 9),
	Weighted_Pressure_Plate_Light_Power_10(Material.GOLD_PLATE, 10),
	Weighted_Pressure_Plate_Light_Power_11(Material.GOLD_PLATE, 11),
	Weighted_Pressure_Plate_Light_Power_12(Material.GOLD_PLATE, 12),
	Weighted_Pressure_Plate_Light_Power_13(Material.GOLD_PLATE, 13),
	Weighted_Pressure_Plate_Light_Power_14(Material.GOLD_PLATE, 14),
	Weighted_Pressure_Plate_Light_Power_15(Material.GOLD_PLATE, 15),
	Weighted_Pressure_Plate_Heavy(Material.IRON_PLATE),
	Weighted_Pressure_Plate_Heavy_Power_1(Material.IRON_PLATE, 1),
	Weighted_Pressure_Plate_Heavy_Power_2(Material.IRON_PLATE, 2),
	Weighted_Pressure_Plate_Heavy_Power_3(Material.IRON_PLATE, 3),
	Weighted_Pressure_Plate_Heavy_Power_4(Material.IRON_PLATE, 4),
	Weighted_Pressure_Plate_Heavy_Power_5(Material.IRON_PLATE, 5),
	Weighted_Pressure_Plate_Heavy_Power_6(Material.IRON_PLATE, 6),
	Weighted_Pressure_Plate_Heavy_Power_7(Material.IRON_PLATE, 7),
	Weighted_Pressure_Plate_Heavy_Power_8(Material.IRON_PLATE, 8),
	Weighted_Pressure_Plate_Heavy_Power_9(Material.IRON_PLATE, 9),
	Weighted_Pressure_Plate_Heavy_Power_10(Material.IRON_PLATE, 10),
	Weighted_Pressure_Plate_Heavy_Power_11(Material.IRON_PLATE, 11),
	Weighted_Pressure_Plate_Heavy_Power_12(Material.IRON_PLATE, 12),
	Weighted_Pressure_Plate_Heavy_Power_13(Material.IRON_PLATE, 13),
	Weighted_Pressure_Plate_Heavy_Power_14(Material.IRON_PLATE, 14),
	Weighted_Pressure_Plate_Heavy_Power_15(Material.IRON_PLATE, 15),
	Daylight_Sensor(Material.DAYLIGHT_DETECTOR),
	Daylight_Sensor_Power_1(Material.DAYLIGHT_DETECTOR, 1),
	Daylight_Sensor_Power_2(Material.DAYLIGHT_DETECTOR, 2),
	Daylight_Sensor_Power_3(Material.DAYLIGHT_DETECTOR, 3),
	Daylight_Sensor_Power_4(Material.DAYLIGHT_DETECTOR, 4),
	Daylight_Sensor_Power_5(Material.DAYLIGHT_DETECTOR, 5),
	Daylight_Sensor_Power_6(Material.DAYLIGHT_DETECTOR, 6),
	Daylight_Sensor_Power_7(Material.DAYLIGHT_DETECTOR, 7),
	Daylight_Sensor_Power_8(Material.DAYLIGHT_DETECTOR, 8),
	Daylight_Sensor_Power_9(Material.DAYLIGHT_DETECTOR, 9),
	Daylight_Sensor_Power_10(Material.DAYLIGHT_DETECTOR, 10),
	Daylight_Sensor_Power_11(Material.DAYLIGHT_DETECTOR, 11),
	Daylight_Sensor_Power_12(Material.DAYLIGHT_DETECTOR, 12),
	Daylight_Sensor_Power_13(Material.DAYLIGHT_DETECTOR, 13),
	Daylight_Sensor_Power_14(Material.DAYLIGHT_DETECTOR, 14),
	Daylight_Sensor_Power_15(Material.DAYLIGHT_DETECTOR, 15),
	Inverted_Daylight_Sensor(Material.DAYLIGHT_DETECTOR_INVERTED),
	Inverted_Daylight_Sensor_Power_1(Material.DAYLIGHT_DETECTOR_INVERTED, 1),
	Inverted_Daylight_Sensor_Power_2(Material.DAYLIGHT_DETECTOR_INVERTED, 2),
	Inverted_Daylight_Sensor_Power_3(Material.DAYLIGHT_DETECTOR_INVERTED, 3),
	Inverted_Daylight_Sensor_Power_4(Material.DAYLIGHT_DETECTOR_INVERTED, 4),
	Inverted_Daylight_Sensor_Power_5(Material.DAYLIGHT_DETECTOR_INVERTED, 5),
	Inverted_Daylight_Sensor_Power_6(Material.DAYLIGHT_DETECTOR_INVERTED, 6),
	Inverted_Daylight_Sensor_Power_7(Material.DAYLIGHT_DETECTOR_INVERTED, 7),
	Inverted_Daylight_Sensor_Power_8(Material.DAYLIGHT_DETECTOR_INVERTED, 8),
	Inverted_Daylight_Sensor_Power_9(Material.DAYLIGHT_DETECTOR_INVERTED, 9),
	Inverted_Daylight_Sensor_Power_10(Material.DAYLIGHT_DETECTOR_INVERTED, 10),
	Inverted_Daylight_Sensor_Power_11(Material.DAYLIGHT_DETECTOR_INVERTED, 11),
	Inverted_Daylight_Sensor_Power_12(Material.DAYLIGHT_DETECTOR_INVERTED, 12),
	Inverted_Daylight_Sensor_Power_13(Material.DAYLIGHT_DETECTOR_INVERTED, 13),
	Inverted_Daylight_Sensor_Power_14(Material.DAYLIGHT_DETECTOR_INVERTED, 14),
	Inverted_Daylight_Sensor_Power_15(Material.DAYLIGHT_DETECTOR_INVERTED, 15),
	Redstone_Block(Material.REDSTONE_BLOCK),
	Hopper_Down(Material.HOPPER),
	Hopper_North(Material.HOPPER, 2),
	Hopper_South(Material.HOPPER, 3),
	Hopper_West(Material.HOPPER, 4),
	Hopper_East(Material.HOPPER, 5),
	Hopper_Disabled_Down(Material.HOPPER, 8),
	Hopper_Disabled_North(Material.HOPPER, 10),
	Hopper_Disabled_South(Material.HOPPER, 11),
	Hopper_Disabled_West(Material.HOPPER, 12),
	Hopper_Disabled_East(Material.HOPPER, 13),
	Dropper_North(Material.DROPPER),
	Dropper_South(Material.DROPPER, 3),
	Dropper_West(Material.DROPPER, 4),
	Dropper_East(Material.DROPPER, 5),
	Dropper_Down(Material.DROPPER, 6),
	Dropper_UP(Material.DROPPER, 7),
	Iron_Trapdoor_North_Down(Material.IRON_TRAPDOOR),
	Iron_Trapdoor_South_Down(Material.IRON_TRAPDOOR, 1),
	Iron_Trapdoor_West_Down(Material.IRON_TRAPDOOR, 2),
	Iron_Trapdoor_East_Down(Material.IRON_TRAPDOOR, 3),
	Iron_Trapdoor_North_Down_OPEN(Material.IRON_TRAPDOOR, 4),
	Iron_Trapdoor_South_Down_OPEN(Material.IRON_TRAPDOOR, 5),
	Iron_Trapdoor_West_Down_OPEN(Material.IRON_TRAPDOOR, 6),
	Iron_Trapdoor_East_Down_OPEN(Material.IRON_TRAPDOOR, 7),
	Iron_Trapdoor_North_UP(Material.IRON_TRAPDOOR, 8),
	Iron_Trapdoor_South_UP(Material.IRON_TRAPDOOR, 9),
	Iron_Trapdoor_West_UP(Material.IRON_TRAPDOOR, 10),
	Iron_Trapdoor_East_UP(Material.IRON_TRAPDOOR, 11),
	Iron_Trapdoor_North_UP_OPEN(Material.IRON_TRAPDOOR, 12),
	Iron_Trapdoor_South_UP_OPEN(Material.IRON_TRAPDOOR, 13),
	Iron_Trapdoor_West_UP_OPEN(Material.IRON_TRAPDOOR, 14),
	Iron_Trapdoor_East_UP_OPEN(Material.IRON_TRAPDOOR, 15),
	Spruce_Fence_Gate_Z(Material.SPRUCE_FENCE_GATE, 2),
	Spruce_Fence_Gate_X(Material.SPRUCE_FENCE_GATE, 3),
	Spruce_Fence_Gate_South_OPEN(Material.SPRUCE_FENCE_GATE, 4),
	Spruce_Fence_Gate_West_OPEN(Material.SPRUCE_FENCE_GATE, 5),
	Spruce_Fence_Gate_North_OPEN(Material.SPRUCE_FENCE_GATE, 6),
	Spruce_Fence_Gate_East_OPEN(Material.SPRUCE_FENCE_GATE, 7),
	Birch_Fence_Gate_Z(Material.BIRCH_FENCE_GATE, 2),
	Birch_Fence_Gate_X(Material.BIRCH_FENCE_GATE, 3),
	Birch_Fence_Gate_South_OPEN(Material.BIRCH_FENCE_GATE, 4),
	Birch_Fence_Gate_West_OPEN(Material.BIRCH_FENCE_GATE, 5),
	Birch_Fence_Gate_North_OPEN(Material.BIRCH_FENCE_GATE, 6),
	Birch_Fence_Gate_East_OPEN(Material.BIRCH_FENCE_GATE, 7),
	Jungle_Fence_Gate_Z(Material.JUNGLE_FENCE_GATE, 2),
	Jungle_Fence_Gate_X(Material.JUNGLE_FENCE_GATE, 3),
	Jungle_Fence_Gate_South_OPEN(Material.JUNGLE_FENCE_GATE, 4),
	Jungle_Fence_Gate_West_OPEN(Material.JUNGLE_FENCE_GATE, 5),
	Jungle_Fence_Gate_North_OPEN(Material.JUNGLE_FENCE_GATE, 6),
	Jungle_Fence_Gate_East_OPEN(Material.JUNGLE_FENCE_GATE, 7),
	Dark_Oak_Fence_Gate_Z(Material.DARK_OAK_FENCE_GATE, 2),
	Dark_Oak_Fence_Gate_X(Material.DARK_OAK_FENCE_GATE, 3),
	Dark_Oak_Fence_Gate_South_OPEN(Material.DARK_OAK_FENCE_GATE, 4),
	Dark_Oak_Fence_Gate_West_OPEN(Material.DARK_OAK_FENCE_GATE, 5),
	Dark_Oak_Fence_Gate_North_OPEN(Material.DARK_OAK_FENCE_GATE, 6),
	Dark_Oak_Fence_Gate_East_OPEN(Material.DARK_OAK_FENCE_GATE, 7),
	Acacia_Fence_Gate_Z(Material.ACACIA_FENCE_GATE, 2),
	Acacia_Fence_Gate_X(Material.ACACIA_FENCE_GATE, 3),
	Acacia_Fence_Gate_South_OPEN(Material.ACACIA_FENCE_GATE, 4),
	Acacia_Fence_Gate_West_OPEN(Material.ACACIA_FENCE_GATE, 5),
	Acacia_Fence_Gate_North_OPEN(Material.ACACIA_FENCE_GATE, 6),
	Acacia_Fence_Gate_East_OPEN(Material.ACACIA_FENCE_GATE, 7),
	;
	
	private String idNumber;
	private String idName;
	private Material material;
	private int blockData;
	
	private BlockResource(Material material) {
		this.material = material;
		this.blockData = 0;
	}
	
	private BlockResource(Material material, int blockData) {
		this.material = material;
		this.blockData = blockData;
	}
	
	private BlockResource(String idNumber, String idName, Material material) {
		this.idNumber = idNumber;
		this.idName = idName;
		this.material = material;
		if(idNumber.contains(":")) {
			blockData = Integer.parseInt(idNumber.split(":")[1]);
		}
	}
	
	private BlockResource(String idNumber, String idName, Material material, int blockData) {
		this.idNumber = idNumber;
		this.idName = idName;
		this.material = material;
		this.blockData = blockData;
	}
	
	public String getID() {
		return idNumber;
	}
	
	public String getIDName() {
		return idName;
	}
	
	public Material getMaterial() {
		return material;
	}
	
	public int getBlockMetaData() {
		return blockData;
	}
	
	public static BlockResource getBlockResourceByID(String idNumber) {
		if(idNumber!=null) {
			for(BlockResource block : BlockResource.values()) {
				if(idNumber.equals(block.getID())) {
					return block;
				}
			}
		}
		return null;
	}
	
	public static BlockResource getBlockResourceByIDName(String idName) {
		if(idName!=null) {
			for(BlockResource block : BlockResource.values()) {
				if(idName.equals(block.getIDName())) {
					return block;
				}
			}
		}
		return null;
	}
	
	@SuppressWarnings("deprecation")
	public void placeBlockAt(Location location) {
		if(getMaterial()!=null) {
			location.getBlock().setType(getMaterial());
			if(getBlockMetaData()>0) {
				location.getBlock().setData((byte)getBlockMetaData(), true);
			}
		}
	}
	
	@SuppressWarnings("deprecation")
	public void placeBlockWithUpdateAt(Location location) {
		if(getMaterial()!=null) {
			location.getBlock().setType(getMaterial());
			if(getBlockMetaData()>0) {
				location.getBlock().setData((byte)getBlockMetaData(), true);
			}
			location.getBlock().getState().update();
		}
	}
	
	@SuppressWarnings("deprecation")
	public static void placeBlock(Location location, BlockResource block) {
		location.getBlock().setType(block.getMaterial());
		if(block.getBlockMetaData()>0) {
			location.getBlock().setData((byte)block.getBlockMetaData(), true);
		}
	}
	
	@SuppressWarnings("deprecation")
	public static void placeBlockWithUpdate(Location location, BlockResource block) {
		location.getBlock().setType(block.getMaterial());
		if(block.getBlockMetaData()>0) {
			location.getBlock().setData((byte)block.getBlockMetaData(), true);
		}
		location.getBlock().getState().update();
	}
	
}
